export const Subjects = [
  {
    id: 1,
    subjectName: "Python",
    courseCoordinator: "John Doe",
    dailyAttendance: [
      { date: "23/10", attendanceType: "P" },
      { date: "24/10", attendanceType: "A" },
      { date: "25/10", attendanceType: "P" },
      { date: "26/10", attendanceType: "P" },
      { date: "27/10", attendanceType: "P" },
      { date: "28/10", attendanceType: "-" },
      { date: "29/10", attendanceType: "-" },
      { date: "30/10", attendanceType: "A" },
      { date: "01/10", attendanceType: "P" },
      { date: "02/10", attendanceType: "P" },
      { date: "03/10", attendanceType: "P" },
      { date: "04/10", attendanceType: "P" },
      { date: "05/10", attendanceType: "-" },
      { date: "06/10", attendanceType: "-" },
      { date: "07/10", attendanceType: "P" },
      { date: "08/10", attendanceType: "A" },
      { date: "09/10", attendanceType: "P" },
      { date: "10/10", attendanceType: "P" },
      { date: "11/10", attendanceType: "-" },
      { date: "12/10", attendanceType: "-" },
    ],
  },
  {
    id: 2,
    subjectName: "Electronics Fundamentals",
    courseCoordinator: "John Doe",
    dailyAttendance: [
      { date: "23/10", attendanceType: "P" },
      { date: "24/10", attendanceType: "A" },
      { date: "25/10", attendanceType: "P" },
      { date: "26/10", attendanceType: "P" },
      { date: "27/10", attendanceType: "P" },
      { date: "28/10", attendanceType: "-" },
      { date: "29/10", attendanceType: "-" },
      { date: "30/10", attendanceType: "A" },
      { date: "01/10", attendanceType: "P" },
      { date: "02/10", attendanceType: "P" },
      { date: "03/10", attendanceType: "P" },
      { date: "04/10", attendanceType: "P" },
      { date: "05/10", attendanceType: "P" },
      { date: "06/10", attendanceType: "P" },
      { date: "07/10", attendanceType: "P" },
      { date: "08/10", attendanceType: "P" },
      { date: "09/10", attendanceType: "P" },
      { date: "10/10", attendanceType: "P" },
      { date: "11/10", attendanceType: "A" },
    ],
  },
  {
    id: 3,
    subjectName: "Theory of Computation",
    courseCoordinator: "John Doe",
    dailyAttendance: [
      { date: "23/10", attendanceType: "P" },
      { date: "24/10", attendanceType: "A" },
      { date: "25/10", attendanceType: "P" },
      { date: "26/10", attendanceType: "P" },
      { date: "27/10", attendanceType: "P" },
      { date: "28/10", attendanceType: "-" },
      { date: "29/10", attendanceType: "-" },
      { date: "30/10", attendanceType: "A" },
      { date: "01/10", attendanceType: "P" },
      { date: "02/10", attendanceType: "P" },
      { date: "03/10", attendanceType: "P" },
      { date: "04/10", attendanceType: "P" },
      { date: "05/10", attendanceType: "-" },
      { date: "06/10", attendanceType: "-" },
      { date: "07/10", attendanceType: "P" },
      { date: "08/10", attendanceType: "P" },
      { date: "09/10", attendanceType: "P" },
      { date: "10/10", attendanceType: "A" },
      { date: "11/10", attendanceType: "A" },
    ],
  },
  {
    id: 4,
    subjectName: "Programming Fundamentals",
    courseCoordinator: "John Doe",
    dailyAttendance: [
      { date: "23/10", attendanceType: "P" },
      { date: "24/10", attendanceType: "A" },
      { date: "25/10", attendanceType: "P" },
      { date: "26/10", attendanceType: "P" },
      { date: "27/10", attendanceType: "P" },
      { date: "28/10", attendanceType: "-" },
      { date: "29/10", attendanceType: "-" },
      { date: "30/10", attendanceType: "A" },
      { date: "01/10", attendanceType: "P" },
      { date: "02/10", attendanceType: "A" },
      { date: "03/10", attendanceType: "P" },
      { date: "04/10", attendanceType: "P" },
      { date: "05/10", attendanceType: "-" },
      { date: "06/10", attendanceType: "-" },
      { date: "07/10", attendanceType: "P" },
      { date: "08/10", attendanceType: "P" },
      { date: "09/10", attendanceType: "A" },
      { date: "10/10", attendanceType: "P" },
      { date: "11/10", attendanceType: "A" },
    ],
  },
];
