export const StudentAttendance = [
  {
    studentID: "123123123",
    studentName: "John",
    subjects: [
      {
        subjectID: 1,
        subjectName: "Subject A",
        dailyAttendance: [
          { date: "23/10", attendanceType: "P" },
          { date: "24/10", attendanceType: "A" },
          { date: "25/10", attendanceType: "P" },
          { date: "26/10", attendanceType: "P" },
          { date: "27/10", attendanceType: "A" },
          { date: "28/10", attendanceType: "P" },
          { date: "29/10", attendanceType: "A" },
          { date: "30/10", attendanceType: "P" },
          { date: "31/10", attendanceType: "P" },
          { date: "01/11", attendanceType: "A" },
          { date: "02/11", attendanceType: "P" },
          { date: "03/11", attendanceType: "A" },
          { date: "04/11", attendanceType: "P" },
          { date: "05/11", attendanceType: "A" },
          { date: "06/11", attendanceType: "P" },
          { date: "07/11", attendanceType: "A" },
          { date: "08/11", attendanceType: "P" },
          { date: "09/11", attendanceType: "A" },
          { date: "10/11", attendanceType: "P" },
          { date: "11/11", attendanceType: "A" },
        ],
      },
      {
        subjectID: 2,
        subjectName: "Subject B",
        dailyAttendance: [
          { date: "23/10", attendanceType: "P" },
          { date: "24/10", attendanceType: "A" },
          { date: "25/10", attendanceType: "P" },
          { date: "26/10", attendanceType: "P" },
          { date: "27/10", attendanceType: "A" },
          { date: "28/10", attendanceType: "P" },
          { date: "29/10", attendanceType: "A" },
          { date: "30/10", attendanceType: "P" },
          { date: "31/10", attendanceType: "P" },
          { date: "01/11", attendanceType: "A" },
          { date: "02/11", attendanceType: "P" },
          { date: "03/11", attendanceType: "A" },
          { date: "04/11", attendanceType: "P" },
          { date: "05/11", attendanceType: "A" },
          { date: "06/11", attendanceType: "P" },
          { date: "07/11", attendanceType: "A" },
          { date: "08/11", attendanceType: "P" },
          { date: "09/11", attendanceType: "A" },
          { date: "10/11", attendanceType: "P" },
          { date: "11/11", attendanceType: "A" },
        ],
      },
      {
        subjectID: 3,
        subjectName: "Subject C",
        dailyAttendance: [
          { date: "23/10", attendanceType: "P" },
          { date: "24/10", attendanceType: "A" },
          { date: "25/10", attendanceType: "P" },
          { date: "26/10", attendanceType: "P" },
          { date: "27/10", attendanceType: "A" },
          { date: "28/10", attendanceType: "P" },
          { date: "29/10", attendanceType: "A" },
          { date: "30/10", attendanceType: "P" },
          { date: "31/10", attendanceType: "P" },
          { date: "01/11", attendanceType: "A" },
          { date: "02/11", attendanceType: "P" },
          { date: "03/11", attendanceType: "A" },
          { date: "04/11", attendanceType: "P" },
          { date: "05/11", attendanceType: "A" },
          { date: "06/11", attendanceType: "P" },
          { date: "07/11", attendanceType: "A" },
          { date: "08/11", attendanceType: "P" },
          { date: "09/11", attendanceType: "A" },
          { date: "10/11", attendanceType: "P" },
          { date: "11/11", attendanceType: "A" },
        ],
      },
      {
        subjectID: 4,
        subjectName: "Subject D",
        dailyAttendance: [
          { date: "23/10", attendanceType: "P" },
          { date: "24/10", attendanceType: "A" },
          { date: "25/10", attendanceType: "P" },
          { date: "26/10", attendanceType: "P" },
          { date: "27/10", attendanceType: "A" },
          { date: "28/10", attendanceType: "P" },
          { date: "29/10", attendanceType: "A" },
          { date: "30/10", attendanceType: "P" },
          { date: "31/10", attendanceType: "P" },
          { date: "01/11", attendanceType: "A" },
          { date: "02/11", attendanceType: "P" },
          { date: "03/11", attendanceType: "A" },
          { date: "04/11", attendanceType: "P" },
          { date: "05/11", attendanceType: "A" },
          { date: "06/11", attendanceType: "P" },
          { date: "07/11", attendanceType: "A" },
          { date: "08/11", attendanceType: "P" },
          { date: "09/11", attendanceType: "A" },
          { date: "10/11", attendanceType: "P" },
          { date: "11/11", attendanceType: "A" },
        ],
      },
    ],
  },
  {
    studentID: "456456456",
    studentName: "Jane",
    subjects: [
      {
        subjectID: 5,
        subjectName: "Subject E",
        dailyAttendance: [
          { date: "23/10", attendanceType: "P" },
          { date: "24/10", attendanceType: "A" },
          { date: "25/10", attendanceType: "P" },
          { date: "26/10", attendanceType: "P" },
          { date: "27/10", attendanceType: "A" },
          { date: "28/10", attendanceType: "P" },
          { date: "29/10", attendanceType: "A" },
          { date: "30/10", attendanceType: "P" },
          { date: "31/10", attendanceType: "P" },
          { date: "01/11", attendanceType: "A" },
          { date: "02/11", attendanceType: "P" },
          { date: "03/11", attendanceType: "A" },
          { date: "04/11", attendanceType: "P" },
          { date: "05/11", attendanceType: "A" },
          { date: "06/11", attendanceType: "P" },
          { date: "07/11", attendanceType: "A" },
          { date: "08/11", attendanceType: "P" },
          { date: "09/11", attendanceType: "A" },
          { date: "10/11", attendanceType: "P" },
          { date: "11/11", attendanceType: "A" },
        ],
      },
      {
        subjectID: 6,
        subjectName: "Subject F",
        dailyAttendance: [
          { date: "23/10", attendanceType: "P" },
          { date: "24/10", attendanceType: "A" },
          { date: "25/10", attendanceType: "P" },
          { date: "26/10", attendanceType: "P" },
          { date: "27/10", attendanceType: "A" },
          { date: "28/10", attendanceType: "P" },
          { date: "29/10", attendanceType: "A" },
          { date: "30/10", attendanceType: "P" },
          { date: "31/10", attendanceType: "P" },
          { date: "01/11", attendanceType: "A" },
          { date: "02/11", attendanceType: "P" },
          { date: "03/11", attendanceType: "A" },
          { date: "04/11", attendanceType: "P" },
          { date: "05/11", attendanceType: "A" },
          { date: "06/11", attendanceType: "P" },
          { date: "07/11", attendanceType: "A" },
          { date: "08/11", attendanceType: "P" },
          { date: "09/11", attendanceType: "A" },
          { date: "10/11", attendanceType: "P" },
          { date: "11/11", attendanceType: "A" },
        ],
      },
      {
        subjectID: 7,
        subjectName: "Subject G",
        dailyAttendance: [
          { date: "23/10", attendanceType: "P" },
          { date: "24/10", attendanceType: "A" },
          { date: "25/10", attendanceType: "P" },
          { date: "26/10", attendanceType: "P" },
          { date: "27/10", attendanceType: "A" },
          { date: "28/10", attendanceType: "P" },
          { date: "29/10", attendanceType: "A" },
          { date: "30/10", attendanceType: "P" },
          { date: "31/10", attendanceType: "P" },
          { date: "01/11", attendanceType: "A" },
          { date: "02/11", attendanceType: "P" },
          { date: "03/11", attendanceType: "A" },
          { date: "04/11", attendanceType: "P" },
          { date: "05/11", attendanceType: "A" },
          { date: "06/11", attendanceType: "P" },
          { date: "07/11", attendanceType: "A" },
          { date: "08/11", attendanceType: "P" },
          { date: "09/11", attendanceType: "A" },
          { date: "10/11", attendanceType: "P" },
          { date: "11/11", attendanceType: "A" },
        ],
      },
      {
        subjectID: 8,
        subjectName: "Subject H",
        dailyAttendance: [
          { date: "23/10", attendanceType: "P" },
          { date: "24/10", attendanceType: "A" },
          { date: "25/10", attendanceType: "P" },
          { date: "26/10", attendanceType: "P" },
          { date: "27/10", attendanceType: "A" },
          { date: "28/10", attendanceType: "P" },
          { date: "29/10", attendanceType: "A" },
          { date: "30/10", attendanceType: "P" },
          { date: "31/10", attendanceType: "P" },
          { date: "01/11", attendanceType: "A" },
          { date: "02/11", attendanceType: "P" },
          { date: "03/11", attendanceType: "A" },
          { date: "04/11", attendanceType: "P" },
          { date: "05/11", attendanceType: "A" },
          { date: "06/11", attendanceType: "P" },
          { date: "07/11", attendanceType: "A" },
          { date: "08/11", attendanceType: "P" },
          { date: "09/11", attendanceType: "A" },
          { date: "10/11", attendanceType: "P" },
          { date: "11/11", attendanceType: "A" },
        ],
      },
    ],
  },
  // Add data for additional students
];
